version: '3.1'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: predrag
      MYSQL_DATABASE: voznipark
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db 
      MYSQL_ROOT_PASSWORD: predrag 
    depends_on:
      - db 

volumes:
  dbdata:  # persistentni volumen za MySQL
